language: node_js
os:
  - linux
node_js:
  - "lts/*"

before_install:
  - |
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  # temporarily disabled until travis-ci release body bug is fixed
  # - sudo apt-get update -q
  # - sudo apt-get install -y jq
  # - npm i -g changelog-parser

cache: npm

script:
  - npm run lint
  - npm run compile
  - npm run test

before_deploy:
  - npm install -g vsce
  - vsce package
  - export RELEASE_TITLE="v$(node -p "require('./package.json').version")"
  # temporarily disabled until travis-ci release body bug is fixed
  # - export RELEASE_DESCRIPTION="$(changelog-parser CHANGELOG.md | jq -r '.versions | .[0] | .body')"

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_ACCESS_TOKEN
    name: $RELEASE_TITLE
    # temporarily disabled until travis-ci release body bug is fixed
    # body: $RELEASE_DESCRIPTION
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      repo: felixjb/testify
      branch: master
      tags: true
  - provider: script
    script: vsce publish -p $VSCE_MKT_PLACE_ACCESS_TOKEN
    skip_cleanup: true
    on:
      repo: felixjb/testify
      branch: master
      tags: true
