language: node_js
os:
  - linux
node_js:
  - "lts/*"

before_install:
  - |
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

cache: npm

script:
  - npm run lint
  - npm run compile
  - npm run test

before_deploy:
  - npm install -g vsce
  - vsce package
  - curl https://github.com/lindell/github-release-cli/releases/download/LATEST_RELEASE/github-releaser-travis -L --output github-releaser && chmod +x github-releaser
  - export RELEASE_DESCRIPTION=$(envsubst < ./CHANGELOG.md)
  - export RELEASE_TITLE="v$(node -p "require('./package.json').version")"

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_ACCESS_TOKEN
    name: $RELEASE_TITLE
    body: $RELEASE_DESCRIPTION
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      repo: felixjb/testify
      branch: master
  - provider: script
    script: vsce publish -p $VSCE_MKT_PLACE_ACCESS_TOKEN
    skip_cleanup: true
    on:
      repo: felixjb/testify
      branch: master
